# Generated by Django 5.0 on 2026-05-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='mascot',
        ),
        migrations.RemoveField(
            model_name='team',
            name='school_name',
        ),
        migrations.AddField(
            model_name='team',
            name='level',
            field=models.CharField(choices=[('Varsity', 'Varsity'), ('JV', 'Junior Varsity'), ('B-Squad', 'B-Squad')], default='Varsity', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
