# Generated by Django 5.0 on 2026-05-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='mascot',
        ),
        migrations.RemoveField(
            model_name='team',
            name='school_name',
        ),
        migrations.AddField(
            model_name='role',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='level',
            field=models.CharField(blank=True, choices=[('Varsity', 'Varsity'), ('JV', 'Junior Varsity'), ('B-Squad', 'B-Squad')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
