# Generated by Django 5.0 on 2026-05-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Rule Set', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('jazz_min_time', models.IntegerField(default=120)),
                ('jazz_max_time', models.IntegerField(default=150)),
                ('kick_min_time', models.IntegerField(default=135)),
                ('kick_max_time', models.IntegerField(default=165)),
                ('kick_min_count', models.IntegerField(default=35)),
                ('kick_max_count', models.IntegerField(default=55)),
                ('varsity_min_competitors', models.IntegerField(default=5)),
                ('varsity_jazz_max_competitors', models.IntegerField(default=26)),
                ('varsity_kick_max_competitors', models.IntegerField(default=34)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
