# Generated by Django 5.0 on 2026-05-11 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeScoreSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(choices=[('JAZZ', 'Jazz'), ('KICK', 'Kick')], max_length=10)),
                ('skills_turns', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skills_leaps_jumps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('kicks_technique', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('kicks_height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('choreo_creativity', models.PositiveSmallIntegerField()),
                ('choreo_visual_effect', models.PositiveSmallIntegerField()),
                ('diff_routine', models.PositiveSmallIntegerField()),
                ('diff_formations', models.PositiveSmallIntegerField()),
                ('diff_skills_or_kicks', models.PositiveSmallIntegerField()),
                ('exec_placement_control', models.PositiveSmallIntegerField()),
                ('exec_accuracy', models.PositiveSmallIntegerField()),
                ('routine_effectiveness', models.PositiveSmallIntegerField()),
                ('time_deduction', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('kick_deduction', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('other_deduction', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('subtotal', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_sheets', to='meets.teamentry')),
            ],
        ),
        migrations.CreateModel(
            name='KCTEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_competitors', models.PositiveIntegerField()),
                ('routine_time_seconds', models.PositiveIntegerField()),
                ('kick_count', models.PositiveIntegerField(blank=True, null=True)),
                ('jazz_team_turn_performed', models.BooleanField(default=True)),
                ('jazz_team_leap_jump_performed', models.BooleanField(default=True)),
                ('falls_observed', models.BooleanField(default=False)),
                ('dangerous_move_observed', models.BooleanField(default=False)),
                ('kct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kct_entries', to='meets.teamentry')),
            ],
        ),
    ]
