# Generated by Django 5.0 on 2026-05-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kctentry',
            name='num_competitors',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
