# Generated by Django 5.0 on 2026-05-14 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0001_initial'),
        ('meets', '0002_meet_dq_by_meet_dq_reason_meet_dq_timestamp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='judgescoresheet',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='judgescoresheet',
            unique_together={('judge', 'team_entry')},
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
