# Generated by Django 5.0 on 2026-05-11 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KCTEntry',
        ),
    ]
