# Generated by Django 5.0 on 2026-05-14 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meets', '0003_ruleset_meet_ruleset_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('DANGEROUS_MOVE', 'Dangerous Move'), ('ILLEGAL_SKILL', 'Illegal Skill'), ('SAFETY', 'Safety'), ('OTHER', 'Other')], max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_dqs', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_dqs', to=settings.AUTH_USER_MODEL)),
                ('team_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dq_entries', to='meets.teamentry')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('FALL', 'Fall'), ('DANGEROUS_MOVE', 'Dangerous Move'), ('ILLEGAL_SKILL', 'Illegal Skill'), ('SAFETY', 'Safety'), ('TIME', 'Time Violation'), ('KICK', 'Kick Count Violation'), ('COMPETITOR', 'Competitor Count'), ('OTHER', 'Other')], max_length=32)),
                ('severity', models.CharField(choices=[('WARNING', 'Warning'), ('POTENTIAL_DEDUCTION', 'Potential Deduction'), ('DEDUCTION', 'Deduction')], default='POTENTIAL_DEDUCTION', max_length=32)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_action', models.CharField(blank=True, help_text='APPLY_DEDUCTION / WARNING_ONLY / NO_ACTION', max_length=32)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issues', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to=settings.AUTH_USER_MODEL)),
                ('team_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='meets.teamentry')),
            ],
        ),
    ]
