# Generated by Django 5.0 on 2026-05-18 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0008_remove_meet_judges_remove_meet_kcts_judgeassignment_and_more'),
        ('superior', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dqentry',
            name='team_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dq_entry', to='meets.teamentry'),
        ),
    ]
