# Generated by Django 5.0 on 2026-05-16 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meets', '0006_remove_teamentry_kct_kick_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('points', models.DecimalField(decimal_places=1, max_digits=4)),
                ('per_occurrence', models.BooleanField(default=True)),
                ('applies_to_jazz', models.BooleanField(default=True)),
                ('applies_to_kick', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('deduction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deductions.deductiontype')),
                ('team_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_deductions', to='meets.teamentry')),
            ],
        ),
    ]
