# Generated by Django 5.0 on 2026-05-11 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('rule_reference', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('division', models.CharField(choices=[('JAZZ', 'Jazz'), ('KICK', 'High Kick'), ('BOTH', 'Both')], default='BOTH', max_length=10)),
                ('penalty_type', models.CharField(choices=[('DQ', 'Disqualification'), ('POINT', 'Point Deduction'), ('WARNING', 'Warning')], max_length=20)),
                ('points', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('max_points', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('per_occurrence', models.BooleanField(default=False)),
                ('per_judge', models.BooleanField(default=False)),
                ('minor_or_flagrant', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('judges_reporting', models.PositiveIntegerField(default=1)),
                ('minor', models.BooleanField(default=False)),
                ('flagrant', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('deduction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deductions.deductiontype')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('team_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='meets.teamentry')),
            ],
        ),
    ]
