# Generated by Django 5.0 on 2026-05-09 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('site', models.CharField(max_length=255)),
                ('class_level', models.CharField(choices=[('A', 'A'), ('AA', 'AA'), ('AAA', 'AAA'), ('CONF', 'Conference')], max_length=10)),
                ('division', models.CharField(choices=[('JAZZ', 'Jazz'), ('KICK', 'Kick')], max_length=10)),
                ('judges', models.ManyToManyField(related_name='judged_meets', to=settings.AUTH_USER_MODEL)),
                ('kcts', models.ManyToManyField(related_name='kct_meets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_order', models.PositiveBigIntegerField()),
                ('num_competitors', models.PositiveBigIntegerField()),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='meets.meet')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
        ),
    ]
