# Generated by Django 5.0 on 2026-05-09 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamentry',
            name='num_competitors',
        ),
    ]
