# Generated by Django 5.0 on 2026-05-14 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='dq_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dq_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meet',
            name='dq_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meet',
            name='dq_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meet',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meet',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meet',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamentry',
            name='final_placement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamentry',
            name='final_rank_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamentry',
            name='final_total_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
