# Generated by Django 5.0 on 2026-05-11 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamentry',
            name='school',
        ),
        migrations.AlterField(
            model_name='teamentry',
            name='meet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meets.meet'),
        ),
        migrations.AlterField(
            model_name='teamentry',
            name='performance_order',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
