# Generated by Django 5.0 on 2026-05-14 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0002_meet_dq_by_meet_dq_reason_meet_dq_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Rule Set', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('jazz_min_time', models.IntegerField(default=120)),
                ('jazz_max_time', models.IntegerField(default=150)),
                ('kick_min_time', models.IntegerField(default=135)),
                ('kick_max_time', models.IntegerField(default=165)),
                ('kick_min_count', models.IntegerField(default=35)),
                ('kick_max_count', models.IntegerField(default=55)),
                ('varsity_min_competitors', models.IntegerField(default=5)),
                ('varsity_jazz_max_competitors', models.IntegerField(default=26)),
                ('varsity_kick_max_competitors', models.IntegerField(default=34)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='meet',
            name='ruleset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meets.ruleset'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(choices=[('VARSITY', 'Varsity'), ('JV', 'Junior Varsity'), ('BSQUAD', 'B-Squad')], default='VARSITY', max_length=10)),
                ('division', models.CharField(choices=[('JAZZ', 'Jazz'), ('KICK', 'Kick')], default='JAZZ', max_length=10)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meets.meet')),
            ],
        ),
    ]
