# Generated by Django 5.0 on 2026-05-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0002_remove_teamentry_school_alter_teamentry_meet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamentry',
            name='final_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamentry',
            name='placement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamentry',
            name='prelim_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
