# Generated by Django 5.0 on 2026-05-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0002_remove_teamentry_num_competitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamentry',
            name='verified_by_tabulator',
            field=models.BooleanField(default=False),
        ),
    ]
