# Generated by Django 5.0 on 2026-05-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0003_ruleset_meet_ruleset_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamentry',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
