# Generated by Django 5.0 on 2026-05-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0003_teamentry_verified_by_tabulator'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='num_finalists',
            field=models.IntegerField(default=6),
        ),
    ]
