# Generated by Django 5.0 on 2026-05-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0004_teamentry_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamentry',
            name='kct_kick_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamentry',
            name='kct_leap_jump_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamentry',
            name='kct_time_seconds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamentry',
            name='kct_turn_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
