# Generated by Django 5.0 on 2026-05-15 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0005_teamentry_kct_kick_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamentry',
            name='kct_kick_count',
        ),
        migrations.RemoveField(
            model_name='teamentry',
            name='kct_leap_jump_confirmed',
        ),
        migrations.RemoveField(
            model_name='teamentry',
            name='kct_time_seconds',
        ),
        migrations.RemoveField(
            model_name='teamentry',
            name='kct_turn_confirmed',
        ),
    ]
