# Generated by Django 5.0 on 2026-05-18 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0007_alter_meet_locked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='judges',
        ),
        migrations.RemoveField(
            model_name='meet',
            name='kcts',
        ),
        migrations.CreateModel(
            name='JudgeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_number', models.PositiveSmallIntegerField()),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meets.meet')),
            ],
            options={
                'ordering': ['judge_number'],
                'unique_together': {('meet', 'judge_number')},
            },
        ),
        migrations.CreateModel(
            name='KCTAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kct_number', models.PositiveSmallIntegerField()),
                ('kct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meets.meet')),
            ],
            options={
                'ordering': ['kct_number'],
                'unique_together': {('meet', 'kct_number')},
            },
        ),
    ]
