# Generated by Django 5.0 on 2026-05-18 23:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0008_remove_meet_judges_remove_meet_kcts_judgeassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='judges',
            field=models.ManyToManyField(related_name='judged_meets', through='meets.JudgeAssignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meet',
            name='kcts',
            field=models.ManyToManyField(related_name='kct_meets', through='meets.KCTAssignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
