# Generated by Django 5.0 on 2026-05-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0009_meet_judges_meet_kcts'),
    ]

    operations = [
        migrations.AddField(
            model_name='kctassignment',
            name='division',
            field=models.CharField(choices=[('JAZZ', 'Jazz'), ('KICK', 'Kick')], default='Jazz', max_length=10),
            preserve_default=False,
        ),
    ]
