# Generated by Django 5.0 on 2026-05-13 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KCTEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_competitors', models.PositiveIntegerField()),
                ('routine_time_seconds', models.PositiveIntegerField()),
                ('kick_count', models.PositiveIntegerField(blank=True, null=True)),
                ('jazz_team_turn_performed', models.BooleanField(default=True)),
                ('jazz_team_leap_jump_performed', models.BooleanField(default=True)),
                ('falls_observed', models.BooleanField(default=False)),
                ('dangerous_move_observed', models.BooleanField(default=False)),
                ('kct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kct_entries', to='meets.teamentry')),
            ],
        ),
    ]
