# Generated by Django 5.0 on 2026-05-14 01:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kct', '0001_initial'),
        ('meets', '0002_meet_dq_by_meet_dq_reason_meet_dq_timestamp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kctentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kctentry',
            name='kct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kct_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='kctentry',
            unique_together={('team_entry', 'kct')},
        ),
    ]
