# Generated by Django 5.0 on 2026-05-15 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kct', '0002_kctentry_created_at_alter_kctentry_kct_and_more'),
        ('meets', '0005_teamentry_kct_kick_count_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kctentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='kctentry',
            name='jazz_leap_jump_performed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kctentry',
            name='jazz_team_turn_performed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kctentry',
            name='kick_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kctentry',
            name='num_competitors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kctentry',
            name='routine_time_seconds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kctentry',
            name='team_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kct_entry', to='meets.teamentry'),
        ),
        migrations.RemoveField(
            model_name='kctentry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='kctentry',
            name='jazz_team_leap_jump_performed',
        ),
        migrations.RemoveField(
            model_name='kctentry',
            name='kct',
        ),
    ]
