# Generated by Django 5.0 on 2026-05-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kct', '0003_alter_kctentry_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kctentry',
            name='falls_observed',
            field=models.BooleanField(default=False),
        ),
    ]
