# Generated by Django 5.0 on 2026-05-21 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kct', '0004_alter_kctentry_falls_observed'),
        ('meets', '0009_meet_judges_meet_kcts'),
    ]

    operations = [
        migrations.AddField(
            model_name='kctentry',
            name='kct_number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kctentry',
            name='team_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kct_entries', to='meets.teamentry'),
        ),
        migrations.AlterUniqueTogether(
            name='kctentry',
            unique_together={('team_entry', 'kct_number')},
        ),
    ]
