# Generated by Django 5.0 on 2026-05-09 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_system', models.CharField(choices=[('A', 'Rank A (7-8 judges)'), ('B', 'Rank B (5-6 judges)'), ('C', 'Rank C (4 or fewer judges)')], max_length=1)),
                ('ranks_list', models.CharField(choices=[('A', 'Rank A (7-8 judges)'), ('B', 'Rank B (5-6 judges)'), ('C', 'Rank C (4 or fewer judges)')], max_length=1)),
                ('dropped_ranks', models.JSONField(default=list)),
                ('rank_total', models.PositiveIntegerField()),
                ('final_place', models.PositiveIntegerField(blank=True, null=True)),
                ('disqualified', models.BooleanField(default=False)),
                ('team_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='meets.teamentry')),
            ],
        ),
    ]
