# Generated by Django 5.0 on 2026-05-14 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabulation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamResult',
        ),
    ]
